#!/bin/bash

SBT_BOOT_DIR=$HOME/.sbt/boot/

if [ ! -d "$SBT_BOOT_DIR" ]; then
  mkdir -p $SBT_BOOT_DIR
fi

cat /dev/null | java -Dfile.encoding=UTF8 -Xmx1G -XX:MaxPermSize=250m -XX:+UseCompressedOops \
    -Dhttp.proxyHost=proxy.gutest.gnl -Dhttp.proxyPort=3128 \
    -Dsbt.log.noformat=true \
    -Dbuild.number="$BUILD_NUMBER" \
    -Dbuild.vcs.number="$BUILD_VCS_NUMBER" \
    -Djava.awt.headless=true \
    -Dint.service.domain="integration.build" \
    -jar sbt-launch-0.11.0.jar "$@"

SBT_EXIT=$?

cd tools
java -jar js.jar wrapper.js ../**/src/main/webapp/static/js/*.js

JSHINT_EXIT=$?

if [ $SBT_EXIT == "0" -a $JSHINT_EXIT == "0" ]; then
    exit 0
else
    exit 1
fi
